project:
  type: website
  output-dir: docs

website:
  title: "Siagro+"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - AA.qmd
      - DR.qmd
      - SAN.qmd
      - IC.qmd
      - CC.qmd
      - contact.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



